import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from 'react';
import Navigation from "@/components/Navigation";

export const metadata: Metadata = {
  title: "Tipad",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <Navigation />
          <main className="flex-grow container mx-auto px-4 py-8">{children}</main>
          <footer className="bg-gray-200 p-4 text-center">
            <p>&copy; 2024 Daani'Tipad. All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}